export enum codes {
  ERR_UKNOWN_MESSAGE_STATUS = 'ERR_UKNOWN_MESSAGE_STATUS',
  ERR_UNEXPECTED_DELIVERY_RECORD_STATUS = 'ERR_UNEXPECTED_DELIVERY_RECORD_STATUS',
  ERR_UNKNOWN_PUBLISH_CONFIG_TYPE = 'ERR_UNKNOWN_PUBLISH_CONFIG_TYPE',
  ERR_UNKNOWN_SIGNATURE_POLICY = 'ERR_UNKNOWN_SIGNATURE_POLICY',
}
