name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

permissions:
  id-token: write       # Required for OIDC
  contents: write       # Required to create a Github release
  pull-requests: write  # Required to add tags to pull requests      

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm build
      # The `events` is used in `test/utils/create-pubsub.ts` and aegir complaints about it unused dependency
      - run: pnpm aegir dep-check --ignore events
  test-node:
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [lts/*]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm test:node -- --cov --bail -- --exit
      - uses: codecov/codecov-action@v1
  test-node-e2e:
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm test:e2e -- --target node --bail -- --exit
  test-chrome:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: pnpm install
      - run: pnpm test:browser -- -t webworker --bail -- --exit
  test-firefox:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: pnpm install
      - run: pnpm test:browser -- -t webworker --bail -- --browser firefox -- --exit
  maybe-release:
    name: release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [check, test-node, test-chrome]
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: release-please-action
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'

      - uses: actions/checkout@v6
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4        
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
        if: ${{ steps.release.outputs.release_created }}

      - run: pnpm install
        if: ${{ steps.release.outputs.release_created }}

      - run: pnpm build
        if: ${{ steps.release.outputs.release_created }}

      - run: pnpm publish --access public --provenance
        if: ${{ steps.release.outputs.release_created }}
